development: &login
  adapter: postgresql
  host: localhost
  port: 5432
  database: lolcommits_server_development
  username: matt
  password:
  encoding: utf8
  template: template0

test:
  <<: *login
  database: lolcommits_server_test
  min_messages: WARNING
