# example database config (postgresql)
# copy to config/database.yml
development: &login
  adapter: postgresql
  host: localhost
  port: 5432
  database: lolcommits_server_development
  username: root
  password:
  encoding: utf8
  template: template0

test:
  <<: *login
  database: lolcommits_server_test
  min_messages: WARNING
