development:
  url: http://0.0.0.0:7474/
  socket: //localhost:7474/
test:
  url: http://0.0.0.0:7474/
  socket: //localhost:7474/

production:
  url: http://firehose.lolcommits.com:7474
  socket: //firehose.lolcommits.com:7474
